apply plugin: 'com.android.library'
apply plugin: 'org.jetbrains.kotlin.android'
apply plugin: 'expo-module-gradle-plugin'

group = 'com.example.circlemodularwallets'
version = '1.0.0'

def circleMavenUsername = System.getenv('MWSDK_MAVEN_USERNAME') ?: project.findProperty('mwsdk.maven.username')
def circleMavenPassword = System.getenv('MWSDK_MAVEN_PASSWORD') ?: project.findProperty('mwsdk.maven.password')

repositories {
  maven {
    url 'https://maven.pkg.github.com/circlefin/modularwallets-android-sdk'
    credentials {
      username circleMavenUsername ?: ''
      password circleMavenPassword ?: ''
    }
    authentication {
      basic(BasicAuthentication)
    }
  }
}

android {
  namespace 'com.example.circlemodularwallets'

  defaultConfig {
    minSdkVersion 26
    versionName version
  }
}

dependencies {
  implementation 'circle.modularwallets:core:1.5.3'
}
